name: Code Scan

on:
  push:
    branches:
      - "*"
    paths:
      - "force-app/main/default/**"
      - "./manifest"

  workflow_dispatch:

permissions:
  contents: write

jobs:
  code-scan:
    name: Code Scan
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "lts/*"

      - name: Install JDK
        uses: actions/setup-java@v3
        with:
          java-version: "17"
          distribution: "temurin"

      - name: Install Salesforce CLI
        run: |
          npm install @salesforce/cli --global

      # Installing Salesforce Scanner Plugin
      - name: Install Salesforce Scanner Plugin
        run: |
          sf plugins install @salesforce/sfdx-scanner

      # Creating directories for scanner results
      - name: Create Required Directories
        run: |
          mkdir -p code-scanner
          rm -f code-scanner/Results.csv

      # Running Salesforce CLI Scanner
      - name: Run Salesforce Code Scan
        id: code-scan
        continue-on-error: true
        run: |
          sf scanner run --target "./force-app" -e "pmd,eslint,retire-js,sfge" -f csv -o "code-scanner/Results.csv"

      # Adding Timestamp to Scanner Results
      - name: Adding Timestamp to Scanner Results
        if: always()
        run: |
          if [ -f "code-scanner/Results.csv" ]; then
            echo -e "\n----------------------------------------" >> code-scanner/Results.csv
            echo "Code Scan completed at: $(date)" >> code-scanner/Results.csv
            echo "Branch: ${{ github.ref_name }}" >> code-scanner/Results.csv
          fi

      # Commit and Push Scanner Results
      - name: Commit and Push Scanner Results
        if: always()
        run: |
          if [ -f "code-scanner/Results.csv" ]; then
            git config --local user.email "github-actions[bot]@users.noreply.github.com"
            git config --local user.name "github-actions[bot]"
            git add code-scanner/Results.csv
            git commit -m "Add code scan results [skip ci]" || echo "No changes to commit"
            git push https://${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git HEAD:${{ github.ref }} || echo "Failed to push changes"
          fi
